# Generated by Django 3.0.14 on 2023-08-08 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.course')),
                ('p_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.place')),
            ],
        ),
    ]
